### PR TITLE
Add Makefile to create gerbers from *.kicad_pcb.

### PR DESCRIPTION
**Pull request by hzeller**
This also prepares the possibility to add a %%gitversion%%
string somewhere on the silkscreen which is replaced with the current
git version (but no such silkscreen is added in this commit).

### CODE REVIEW

**Comment by hzeller** [comment]
This is essentially similar to the pull request I already sent with the PocketBone ( https://github.com/jadonk/PocketBone/pull/15 ).

I did not add a `%%gitversion%%` silkscreen yet on the board - it would fit naturally in the center of the board on the bottom, but this is also where you usually have the PocketBeagle logo, so not sure where a preferred place would be.
(But if this is the 'community version', then I could add some smack center).

**Comment by hzeller** [comment]
Note, this creates a directory `plot/` currently in KiCAD, which is of course alongside the existing, checked-in `plots/` dir. So the plots/ directory should probably be removed or we change the Makefile to write into plots/ also ... I leave that up to you and @mwelling

So this pull request requires some more decisions for you.

One thing is: the Gerber files are names a little differently: the files in the `plots/` directory can not be simply packed up and send to OshPark, they have trouble recognizing the names, while the files created with my script generate Gerber files and a zip file with names that OshPark can understand out of the box.

**Comment by hzeller** [comment]
I have one on order now to to see how things turn out. The Makefile-generated zip-file uploads to OshPark without problem.
Here, I added a `%%gitversion%%` on the bottom of the board. You can also see the slightly moved silkscreen of the connector, which is pull request #1

**Comment by mwelling** [comment]
Thanks @hzeller! I don't have write access to this repository though.
Perhaps @jadonk can merge this upon approval.

We can remove the stale Gerbers from the plots directory.

**Pull request merged**
