### PR TITLE
Sanitized schematic.

### PR DESCRIPTION
**Pull request by hemalchevli**
Removed "Pin not connected" errors. Net labels terminate on wire endpoints. Fixed P1 P2 symbol pin number overlap. Added schematic heading.

### CODE REVIEW

**Comment by jadonk** [comment]
Hey @mwelling, can you confirm this?

**Comment by mwelling** [comment]
@jadonk all of the changes appear to be fine. The most marked improvement being removal of the text overlaps on the connectors.

Acked-by: Michael Welling <mwelling@ieee.org>

**Comment by mwelling** [comment]
We may want to update the schematic pdf in the plots directory to reflect these changes.

**Comment by hemalchevli** [comment]
I'll raise another PR for the same.

**Comment by hemalchevli** [comment]
Looks like I cant open another PR from same branch. Good news is the updated PDF is now in the list of files changed. Merging this PR will update the PDF as well.

**Comment by mwelling** [comment]
Okay @jadonk this should be good to merge now with my ack.

**Pull request merged**
